apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-todolist.fullname" . }}-configmap
data:
  database.properties: |-
    database.url=jdbc:mysql://mysql-host:3306/todolist
    database.username=admin
    database.password=secretpassword
