apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-todolist.fullname" . }}-deployment
  namespace: api-todolist
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart-todolist.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chart-todolist.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
