apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-todolist.fullname" . }}-secret
type: Opaque
data:
  api-key: {{ .Files.Get "files/api-key.txt" | b64enc | quote }}
  db-password: {{ .Files.Get "files/db-password.txt" | b64enc | quote }}
