apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-todolist.fullname" . }}-service
  namespace: api-todolist
spec:
  selector:
    app: {{ include "chart-todolist.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
